### ISSUE TITLE
Website functionality not working after using Restore feature.

### ISSUE THREAD

**Issue by Ruke256** [amanharwara/chartr#7]
After using the restore feature just to try if it's working with topster backup charts (it doesn't), most of the buttons are not working for me anymore besides certain features like the Report Bug/Issue, Download, and the Add Album function.

**Comment by amanharwara** [comment]
Could you possibly share the .json file so I can test it?

**Comment by Ruke256** [comment]
[topsters2.2021-09-12T00_41_17.zip](https://github.com/amanharwara/chartr/files/7153805/topsters2.2021-09-12T00_41_17.zip)

Here.

**Comment by amanharwara** [comment]
This seems to be an empty chart? Also, works fine after I use the restore feature.

**Comment by Ruke256** [comment]
Hmm, weird... It might be surrounding my cookie data. Thank you though.
